baseURL = "/"
languageCode = "en-us"
title = "Woahuh's site"
theme = "PaperMod"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2

  [[menu.main]]
    name = "All Posts"
    url = "/blog/"
    parent = "blog"
    weight = 1

  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    parent = "blog"
    weight = 2
